// This file is auto-generated by @hey-api/openapi-ts

export const ErrorResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string',
            description: 'Human-readable error description.',
            example: 'Validation error: node_id is required'
        }
    }
} as const;

export const GeoJsonMultiLineStringSchema = {
    type: 'object',
    required: [
        'type',
        'coordinates'
    ],
    properties: {
        coordinates: {
            type: 'array',
            items: {
                type: 'array',
                items: {
                    type: 'array',
                    items: {
                        type: 'number',
                        format: 'double'
                    }
                }
            },
            description: 'GeoJSON coordinates in `[longitude, latitude]`.'
        },
        type: {
            type: 'string',
            example: 'MultiLineString'
        }
    }
} as const;

export const IngestAcceptedResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string',
            description: 'Human-readable success description.',
            example: 'Ingest accepted'
        }
    }
} as const;

export const IngestDtoSchema = {
    type: 'object',
    required: [
        'node_id',
        'count',
        'age_in_seconds'
    ],
    properties: {
        age_in_seconds: {
            type: 'integer',
            format: 'int32',
            maximum: 31536000,
            minimum: 0
        },
        count: {
            type: 'integer',
            format: 'int32',
            minimum: 0
        },
        node_id: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const NodeDtoSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'status',
        'latitude',
        'longitude',
        'send_frequency_seconds',
        'created_at'
    ],
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        latitude: {
            type: 'number',
            format: 'double'
        },
        longitude: {
            type: 'number',
            format: 'double'
        },
        name: {
            type: 'string'
        },
        send_frequency_seconds: {
            type: 'integer',
            format: 'int64',
            maximum: 86400,
            minimum: 1
        },
        status: {
            $ref: '#/components/schemas/NodeStatus'
        }
    }
} as const;

export const NodeStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'online',
        'unstable',
        'offline'
    ]
} as const;

export const TimeseriesBucketSchema = {
    type: 'string',
    enum: [
        'hour',
        'day',
        'week'
    ]
} as const;

export const TimeseriesPointDtoSchema = {
    type: 'object',
    required: [
        'bucket_start',
        'total_count'
    ],
    properties: {
        bucket_start: {
            type: 'string',
            format: 'date-time'
        },
        total_count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const TrailDetailDtoSchema = {
    type: 'object',
    required: [
        'id',
        'source',
        'name',
        'tags'
    ],
    properties: {
        geometry_geojson: {
            $ref: '#/components/schemas/GeoJsonMultiLineString'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        source_id: {
            type: [
                'integer',
                'null'
            ],
            format: 'int64'
        },
        tags: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            },
            propertyNames: {
                type: 'string'
            }
        }
    }
} as const;

export const TrailListItemDtoSchema = {
    type: 'object',
    required: [
        'id',
        'source',
        'name'
    ],
    properties: {
        geometry_geojson: {
            $ref: '#/components/schemas/GeoJsonMultiLineString'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        source_id: {
            type: [
                'integer',
                'null'
            ],
            format: 'int64'
        }
    }
} as const;

export const TrailTimeseriesQueryDtoSchema = {
    type: 'object',
    required: [
        'bucket',
        'from',
        'to'
    ],
    properties: {
        bucket: {
            $ref: '#/components/schemas/TimeseriesBucket',
            description: 'Aggregation bucket. `hour` supports up to 31 days, `day` and `week` support up to 1 year.'
        },
        from: {
            type: 'string',
            format: 'date-time',
            description: 'Range start (inclusive), must be earlier than `to`.'
        },
        to: {
            type: 'string',
            format: 'date-time',
            description: 'Range end (exclusive); max range is 1 year (`day`/`week`) or 31 days (`hour`).'
        },
        tolerance_m: {
            type: 'number',
            format: 'double',
            description: 'Distance threshold in meters from trail geometry. Defaults to 25m.'
        }
    }
} as const;
