// This file is auto-generated by @hey-api/openapi-ts

export const MeasurementDtoSchema = {
    type: 'object',
    required: [
        'wifi',
        'bluetooth'
    ],
    properties: {
        bluetooth: {
            type: 'integer',
            format: 'int32'
        },
        created_at: {
            type: [
                'string',
                'null'
            ],
            format: 'date-time'
        },
        wifi: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;
