// This file is auto-generated by @hey-api/openapi-ts

export const ErrorResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string',
            description: 'Human-readable error description.',
            example: 'Validation error: node_id is required'
        }
    }
} as const;

export const IngestAcceptedResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string',
            description: 'Human-readable success description.',
            example: 'Ingest accepted'
        }
    }
} as const;

export const IngestDtoSchema = {
    type: 'object',
    required: [
        'node_id',
        'count',
        'age_in_seconds'
    ],
    properties: {
        age_in_seconds: {
            type: 'integer',
            format: 'int32',
            maximum: 31536000,
            minimum: 0
        },
        count: {
            type: 'integer',
            format: 'int32',
            minimum: 0
        },
        node_id: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const NodeDtoSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'status',
        'latitude',
        'longitude',
        'send_frequency_seconds',
        'created_at'
    ],
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        latitude: {
            type: 'number',
            format: 'double'
        },
        longitude: {
            type: 'number',
            format: 'double'
        },
        name: {
            type: 'string'
        },
        send_frequency_seconds: {
            type: 'integer',
            format: 'int64',
            maximum: 86400,
            minimum: 1
        },
        status: {
            $ref: '#/components/schemas/NodeStatus'
        }
    }
} as const;

export const NodeStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'online',
        'unstable',
        'offline'
    ]
} as const;

export const TimeseriesBucketSchema = {
    type: 'string',
    enum: [
        'hour',
        'day'
    ]
} as const;

export const TimeseriesPointDtoSchema = {
    type: 'object',
    required: [
        'bucket_start',
        'total_count'
    ],
    properties: {
        bucket_start: {
            type: 'string',
            format: 'date-time'
        },
        total_count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;
