// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMeasurementData, AddMeasurementErrors, AddMeasurementResponses, ListNodesData, ListNodesErrors, ListNodesResponses, MeasurementTimeseriesData, MeasurementTimeseriesErrors, MeasurementTimeseriesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const addMeasurement = <ThrowOnError extends boolean = false>(options: Options<AddMeasurementData, ThrowOnError>) => (options.client ?? client).post<AddMeasurementResponses, AddMeasurementErrors, ThrowOnError>({
    url: '/ingest',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const measurementTimeseries = <ThrowOnError extends boolean = false>(options: Options<MeasurementTimeseriesData, ThrowOnError>) => (options.client ?? client).get<MeasurementTimeseriesResponses, MeasurementTimeseriesErrors, ThrowOnError>({ url: '/measurements/timeseries', ...options });

export const listNodes = <ThrowOnError extends boolean = false>(options?: Options<ListNodesData, ThrowOnError>) => (options?.client ?? client).get<ListNodesResponses, ListNodesErrors, ThrowOnError>({ url: '/nodes', ...options });
