// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMeasurementData, AddMeasurementResponses, GetNodeTrailsData, GetNodeTrailsResponses, GetTrailData, GetTrailNodesData, GetTrailNodesResponses, GetTrailResponses, ListNodesData, ListNodesResponses, ListTrailsData, ListTrailsResponses, MeasurementTimeseriesData, MeasurementTimeseriesResponses, TrailMeasurementTimeseriesData, TrailMeasurementTimeseriesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const listTrails = <ThrowOnError extends boolean = false>(options?: Options<ListTrailsData, ThrowOnError>) => (options?.client ?? client).get<ListTrailsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/geo/trails',
    ...options
});

export const getTrail = <ThrowOnError extends boolean = false>(options: Options<GetTrailData, ThrowOnError>) => (options.client ?? client).get<GetTrailResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/geo/trails/{trail_id}',
    ...options
});

export const getTrailNodes = <ThrowOnError extends boolean = false>(options: Options<GetTrailNodesData, ThrowOnError>) => (options.client ?? client).get<GetTrailNodesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/geo/trails/{trail_id}/nodes',
    ...options
});

export const addMeasurement = <ThrowOnError extends boolean = false>(options: Options<AddMeasurementData, ThrowOnError>) => (options.client ?? client).post<AddMeasurementResponses, unknown, ThrowOnError>({
    url: '/ingest',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const measurementTimeseries = <ThrowOnError extends boolean = false>(options: Options<MeasurementTimeseriesData, ThrowOnError>) => (options.client ?? client).get<MeasurementTimeseriesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/measurements/nodes/{node_id}/timeseries',
    ...options
});

export const trailMeasurementTimeseries = <ThrowOnError extends boolean = false>(options: Options<TrailMeasurementTimeseriesData, ThrowOnError>) => (options.client ?? client).get<TrailMeasurementTimeseriesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/measurements/trails/{trail_id}/timeseries',
    ...options
});

export const listNodes = <ThrowOnError extends boolean = false>(options?: Options<ListNodesData, ThrowOnError>) => (options?.client ?? client).get<ListNodesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/nodes',
    ...options
});

export const getNodeTrails = <ThrowOnError extends boolean = false>(options: Options<GetNodeTrailsData, ThrowOnError>) => (options.client ?? client).get<GetNodeTrailsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/nodes/{node_id}/trails',
    ...options
});
