// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.trailsense.daugt.com' | (string & {});
};

export type ErrorResponse = {
    /**
     * Human-readable error description.
     */
    message: string;
};

export type GeoJsonMultiLineString = {
    /**
     * GeoJSON coordinates in `[longitude, latitude]`.
     */
    coordinates: Array<Array<Array<number>>>;
    type: string;
};

export type IngestAcceptedResponse = {
    /**
     * Human-readable success description.
     */
    message: string;
};

export type IngestDto = {
    age_in_seconds: number;
    count: number;
    node_id: string;
};

export type NodeDto = {
    activation_count?: number | null;
    created_at: string;
    id: string;
    latitude: number;
    longitude: number;
    name: string;
    send_frequency_seconds: number;
    status: NodeStatus;
};

/**
 * Node list query.
 *
 * Ordering rules:
 * - when `date` + `bucket` are provided: `activation_count DESC`, then distance if `lat/lon` exist, then `id`
 * - when only `lat/lon` are provided: distance ascending, then `id`
 * - otherwise: `created_at DESC`, then `id`
 */
export type NodeListQueryDto = {
    bucket?: null | TimeseriesBucket;
    /**
     * Optional date anchor for single-bucket activation stats and activation-based ordering.
     *
     * Must be used together with `bucket`. If omitted, no `activation_count` is returned.
     */
    date?: string | null;
    /**
     * Optional map center latitude (WGS84 / EPSG:4326).
     */
    lat?: number | null;
    /**
     * Hard cap for number of returned nodes. Defaults to 20.
     */
    limit?: number;
    /**
     * Optional map center longitude (WGS84 / EPSG:4326).
     */
    lon?: number | null;
};

export type NodeStatus = 'pending' | 'online' | 'unstable' | 'offline';

export type TimeseriesBucket = 'hour' | 'day' | 'week';

export type TimeseriesPointDto = {
    bucket_start: string;
    total_count: number;
};

export type TrailDetailDto = {
    geometry_geojson?: GeoJsonMultiLineString;
    id: string;
    name: string;
    source: string;
    source_id?: number | null;
    tags: {
        [key: string]: string;
    };
};

export type TrailListItemDto = {
    activation_count?: number | null;
    geometry_geojson?: GeoJsonMultiLineString;
    id: string;
    name: string;
    source: string;
    source_id?: number | null;
};

export type TrailTimeseriesQueryDto = {
    /**
     * Aggregation bucket. `hour` supports up to 31 days, `day` and `week` support up to 1 year.
     */
    bucket: TimeseriesBucket;
    /**
     * Range start (inclusive), must be earlier than `to`.
     */
    from: string;
    /**
     * Range end (exclusive); max range is 1 year (`day`/`week`) or 31 days (`hour`).
     */
    to: string;
    /**
     * Distance threshold in meters from trail geometry. Defaults to 25m.
     */
    tolerance_m?: number;
};

/**
 * Trail list query.
 *
 * Ordering rules:
 * - when `date` + `bucket` are provided: `activation_count DESC`, then distance if `lat/lon` exist, then `id`
 * - when only `lat/lon` are provided: distance ascending, then `id`
 * - otherwise: `created_at DESC`, then `id`
 */
export type TrailsQueryDto = {
    bucket?: null | TimeseriesBucket;
    /**
     * Optional date anchor for single-bucket activation stats and activation-based ordering.
     *
     * Must be used together with `bucket`. If omitted, no `activation_count` is returned.
     */
    date?: string | null;
    /**
     * Include trail geometry/path in the response.
     */
    include_geo?: boolean;
    /**
     * Optional map center latitude (WGS84 / EPSG:4326).
     */
    lat?: number | null;
    /**
     * Hard cap for number of returned trails. Defaults to 20.
     */
    limit?: number;
    /**
     * Optional map center longitude (WGS84 / EPSG:4326).
     */
    lon?: number | null;
};

export type ListTrailsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include trail geometry/path in the response.
         */
        include_geo?: boolean;
        /**
         * Optional map center latitude (WGS84 / EPSG:4326).
         */
        lat?: number;
        /**
         * Optional map center longitude (WGS84 / EPSG:4326).
         */
        lon?: number;
        /**
         * Hard cap for number of returned trails. Defaults to 20.
         */
        limit?: number;
        /**
         * Optional date anchor for single-bucket activation stats and activation-based ordering.
         *
         * Must be used together with `bucket`. If omitted, no `activation_count` is returned.
         */
        date?: string;
        /**
         * Optional aggregation bucket for single-bucket activation stats and activation-based ordering.
         *
         * Must be used together with `date`.
         */
        bucket?: TimeseriesBucket;
    };
    url: '/geo/trails';
};

export type ListTrailsResponses = {
    /**
     * List trails
     */
    200: Array<TrailListItemDto>;
};

export type ListTrailsResponse = ListTrailsResponses[keyof ListTrailsResponses];

export type GetTrailData = {
    body?: never;
    path: {
        /**
         * Trail ID
         */
        trail_id: string;
    };
    query?: {
        /**
         * Include trail geometry/path in the response.
         */
        include_geo?: boolean;
    };
    url: '/geo/trails/{trail_id}';
};

export type GetTrailResponses = {
    /**
     * Trail detail
     */
    200: TrailDetailDto;
};

export type GetTrailResponse = GetTrailResponses[keyof GetTrailResponses];

export type GetTrailNodesData = {
    body?: never;
    path: {
        /**
         * Trail ID
         */
        trail_id: string;
    };
    query?: {
        /**
         * Distance threshold in meters from the trail geometry. Defaults to 25m.
         */
        tolerance_m?: number;
    };
    url: '/geo/trails/{trail_id}/nodes';
};

export type GetTrailNodesResponses = {
    /**
     * Nodes near trail
     */
    200: Array<NodeDto>;
};

export type GetTrailNodesResponse = GetTrailNodesResponses[keyof GetTrailNodesResponses];

export type AddMeasurementData = {
    body: Array<IngestDto>;
    path?: never;
    query?: never;
    url: '/ingest';
};

export type AddMeasurementResponses = {
    /**
     * Ingest accepted
     */
    200: IngestAcceptedResponse;
};

export type AddMeasurementResponse = AddMeasurementResponses[keyof AddMeasurementResponses];

export type MeasurementTimeseriesData = {
    body?: never;
    path: {
        /**
         * Node ID
         */
        node_id: string;
    };
    query: {
        /**
         * Aggregation bucket. `hour` supports up to 31 days, `day` and `week` support up to 1 year.
         */
        bucket: TimeseriesBucket;
        /**
         * Range start (inclusive), must be earlier than `to`.
         */
        from: string;
        /**
         * Range end (exclusive); max range is 1 year (`day`/`week`) or 31 days (`hour`).
         */
        to: string;
    };
    url: '/measurements/nodes/{node_id}/timeseries';
};

export type MeasurementTimeseriesResponses = {
    /**
     * Measurement timeseries for node
     */
    200: Array<TimeseriesPointDto>;
};

export type MeasurementTimeseriesResponse = MeasurementTimeseriesResponses[keyof MeasurementTimeseriesResponses];

export type TrailMeasurementTimeseriesData = {
    body?: never;
    path: {
        /**
         * Trail ID
         */
        trail_id: string;
    };
    query: {
        /**
         * Aggregation bucket. `hour` supports up to 31 days, `day` and `week` support up to 1 year.
         */
        bucket: TimeseriesBucket;
        /**
         * Range start (inclusive), must be earlier than `to`.
         */
        from: string;
        /**
         * Range end (exclusive); max range is 1 year (`day`/`week`) or 31 days (`hour`).
         */
        to: string;
        /**
         * Distance threshold in meters from trail geometry. Defaults to 25m.
         */
        tolerance_m?: number;
    };
    url: '/measurements/trails/{trail_id}/timeseries';
};

export type TrailMeasurementTimeseriesResponses = {
    /**
     * Rounded average measurement timeseries across nodes along a trail
     */
    200: Array<TimeseriesPointDto>;
};

export type TrailMeasurementTimeseriesResponse = TrailMeasurementTimeseriesResponses[keyof TrailMeasurementTimeseriesResponses];

export type ListNodesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional map center latitude (WGS84 / EPSG:4326).
         */
        lat?: number;
        /**
         * Optional map center longitude (WGS84 / EPSG:4326).
         */
        lon?: number;
        /**
         * Hard cap for number of returned nodes. Defaults to 20.
         */
        limit?: number;
        /**
         * Optional date anchor for single-bucket activation stats and activation-based ordering.
         *
         * Must be used together with `bucket`. If omitted, no `activation_count` is returned.
         */
        date?: string;
        /**
         * Optional aggregation bucket for single-bucket activation stats and activation-based ordering.
         *
         * Must be used together with `date`.
         */
        bucket?: TimeseriesBucket;
    };
    url: '/nodes';
};

export type ListNodesResponses = {
    /**
     * List nodes
     */
    200: Array<NodeDto>;
};

export type ListNodesResponse = ListNodesResponses[keyof ListNodesResponses];

export type GetNodeTrailsData = {
    body?: never;
    path: {
        /**
         * Node ID
         */
        node_id: string;
    };
    query?: {
        /**
         * Include trail geometry/path in the response.
         */
        include_geo?: boolean;
        /**
         * Distance threshold in meters from the node point. Defaults to 25m.
         */
        tolerance_m?: number;
    };
    url: '/nodes/{node_id}/trails';
};

export type GetNodeTrailsResponses = {
    /**
     * Trails near node
     */
    200: Array<TrailListItemDto>;
};

export type GetNodeTrailsResponse = GetNodeTrailsResponses[keyof GetNodeTrailsResponses];
