// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.trailsense.daugt.com' | (string & {});
};

export type MeasurementDto = {
    bluetooth: number;
    created_at?: string | null;
    wifi: number;
};

export type AddMeasurementData = {
    body: MeasurementDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/ingest/{id}';
};

export type AddMeasurementResponses = {
    /**
     * Ingest accepted
     */
    200: string;
};

export type AddMeasurementResponse = AddMeasurementResponses[keyof AddMeasurementResponses];
