// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type ErrorResponse = {
    /**
     * Human-readable error description.
     */
    message: string;
};

export type GeoJsonMultiLineString = {
    /**
     * GeoJSON coordinates in `[longitude, latitude]`.
     */
    coordinates: Array<Array<Array<number>>>;
    type: string;
};

export type IngestAcceptedResponse = {
    /**
     * Human-readable success description.
     */
    message: string;
};

export type IngestDto = {
    age_in_seconds: number;
    count: number;
    node_id: string;
};

export type NodeDto = {
    created_at: string;
    id: string;
    latitude: number;
    longitude: number;
    name: string;
    send_frequency_seconds: number;
    status: NodeStatus;
};

export type NodeStatus = 'pending' | 'online' | 'unstable' | 'offline';

export type TimeseriesBucket = 'hour' | 'day' | 'week';

export type TimeseriesPointDto = {
    bucket_start: string;
    total_count: number;
};

export type TrailDetailDto = {
    geometry_geojson?: GeoJsonMultiLineString;
    id: string;
    name: string;
    source: string;
    source_id?: number | null;
    tags: {
        [key: string]: string;
    };
};

export type TrailListItemDto = {
    geometry_geojson?: GeoJsonMultiLineString;
    id: string;
    name: string;
    source: string;
    source_id?: number | null;
};

export type ListTrailsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional bbox min longitude (WGS84 / EPSG:4326).
         */
        min_lon?: number;
        /**
         * Optional bbox min latitude (WGS84 / EPSG:4326).
         */
        min_lat?: number;
        /**
         * Optional bbox max longitude (WGS84 / EPSG:4326).
         */
        max_lon?: number;
        /**
         * Optional bbox max latitude (WGS84 / EPSG:4326).
         */
        max_lat?: number;
        /**
         * Include trail geometry/path in the response. Requires `bbox` to be set.
         */
        include_geo?: boolean;
        /**
         * Hard cap for number of returned trails. Defaults to 50.
         */
        limit?: number;
    };
    url: '/geo/trails';
};

export type ListTrailsResponses = {
    /**
     * List trails
     */
    200: Array<TrailListItemDto>;
};

export type ListTrailsResponse = ListTrailsResponses[keyof ListTrailsResponses];

export type GetTrailData = {
    body?: never;
    path: {
        /**
         * Trail ID
         */
        trail_id: string;
    };
    query?: {
        /**
         * Include trail geometry/path in the response.
         */
        include_geo?: boolean;
    };
    url: '/geo/trails/{trail_id}';
};

export type GetTrailResponses = {
    /**
     * Trail detail
     */
    200: TrailDetailDto;
};

export type GetTrailResponse = GetTrailResponses[keyof GetTrailResponses];

export type GetTrailNodesData = {
    body?: never;
    path: {
        /**
         * Trail ID
         */
        trail_id: string;
    };
    query?: {
        /**
         * Distance threshold in meters from the trail geometry. Defaults to 25m.
         */
        tolerance_m?: number;
    };
    url: '/geo/trails/{trail_id}/nodes';
};

export type GetTrailNodesResponses = {
    /**
     * Nodes near trail
     */
    200: Array<NodeDto>;
};

export type GetTrailNodesResponse = GetTrailNodesResponses[keyof GetTrailNodesResponses];

export type AddMeasurementData = {
    body: Array<IngestDto>;
    path?: never;
    query?: never;
    url: '/ingest';
};

export type AddMeasurementResponses = {
    /**
     * Ingest accepted
     */
    200: IngestAcceptedResponse;
};

export type AddMeasurementResponse = AddMeasurementResponses[keyof AddMeasurementResponses];

export type MeasurementTimeseriesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Node identifier to aggregate measurements for.
         */
        node_id: string;
        /**
         * Aggregation bucket. `hour` supports up to 31 days, `day` and `week` support up to 1 year.
         */
        bucket: TimeseriesBucket;
        /**
         * Range start (inclusive), must be earlier than `to`.
         */
        from: string;
        /**
         * Range end (exclusive); max range is 1 year (`day`/`week`) or 31 days (`hour`).
         */
        to: string;
    };
    url: '/measurements/timeseries';
};

export type MeasurementTimeseriesResponses = {
    /**
     * Measurement timeseries for node
     */
    200: Array<TimeseriesPointDto>;
};

export type MeasurementTimeseriesResponse = MeasurementTimeseriesResponses[keyof MeasurementTimeseriesResponses];

export type ListNodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes';
};

export type ListNodesResponses = {
    /**
     * List nodes
     */
    200: Array<NodeDto>;
};

export type ListNodesResponse = ListNodesResponses[keyof ListNodesResponses];

export type GetNodeTrailsData = {
    body?: never;
    path: {
        /**
         * Node ID
         */
        node_id: string;
    };
    query?: {
        /**
         * Include trail geometry/path in the response.
         */
        include_geo?: boolean;
        /**
         * Distance threshold in meters from the node point. Defaults to 25m.
         */
        tolerance_m?: number;
    };
    url: '/nodes/{node_id}/trails';
};

export type GetNodeTrailsResponses = {
    /**
     * Trails near node
     */
    200: Array<TrailListItemDto>;
};

export type GetNodeTrailsResponse = GetNodeTrailsResponses[keyof GetNodeTrailsResponses];
