// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { addMeasurement, getNodeTrails, getTrail, getTrailNodes, listNodes, listTrails, measurementTimeseries, type Options } from '../sdk.gen';
import type { AddMeasurementData, AddMeasurementResponse, GetNodeTrailsData, GetTrailData, GetTrailNodesData, ListNodesData, ListTrailsData, MeasurementTimeseriesData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const listTrailsQueryKey = (options?: Options<ListTrailsData>) => createQueryKey('listTrails', options);

export const listTrailsQuery = defineQueryOptions((options?: Options<ListTrailsData>) => ({
    key: listTrailsQueryKey(options),
    query: async (context) => {
        const { data } = await listTrails({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getTrailQueryKey = (options: Options<GetTrailData>) => createQueryKey('getTrail', options);

export const getTrailQuery = defineQueryOptions((options: Options<GetTrailData>) => ({
    key: getTrailQueryKey(options),
    query: async (context) => {
        const { data } = await getTrail({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getTrailNodesQueryKey = (options: Options<GetTrailNodesData>) => createQueryKey('getTrailNodes', options);

export const getTrailNodesQuery = defineQueryOptions((options: Options<GetTrailNodesData>) => ({
    key: getTrailNodesQueryKey(options),
    query: async (context) => {
        const { data } = await getTrailNodes({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const addMeasurementMutation = (options?: Partial<Options<AddMeasurementData>>): UseMutationOptions<AddMeasurementResponse, Options<AddMeasurementData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await addMeasurement({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const measurementTimeseriesQueryKey = (options: Options<MeasurementTimeseriesData>) => createQueryKey('measurementTimeseries', options);

export const measurementTimeseriesQuery = defineQueryOptions((options: Options<MeasurementTimeseriesData>) => ({
    key: measurementTimeseriesQueryKey(options),
    query: async (context) => {
        const { data } = await measurementTimeseries({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const listNodesQueryKey = (options?: Options<ListNodesData>) => createQueryKey('listNodes', options);

export const listNodesQuery = defineQueryOptions((options?: Options<ListNodesData>) => ({
    key: listNodesQueryKey(options),
    query: async (context) => {
        const { data } = await listNodes({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getNodeTrailsQueryKey = (options: Options<GetNodeTrailsData>) => createQueryKey('getNodeTrails', options);

export const getNodeTrailsQuery = defineQueryOptions((options: Options<GetNodeTrailsData>) => ({
    key: getNodeTrailsQueryKey(options),
    query: async (context) => {
        const { data } = await getNodeTrails({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
