// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from '@pinia/colada';

import { addMeasurement, type Options } from '../sdk.gen';
import type { AddMeasurementData, AddMeasurementResponse } from '../types.gen';

export const addMeasurementMutation = (options?: Partial<Options<AddMeasurementData>>): UseMutationOptions<AddMeasurementResponse, Options<AddMeasurementData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await addMeasurement({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});
